### ISSUE TITLE
Unable to build on Ubuntu 15.04

### ISSUE THREAD

**Issue by hzulla** [mono/f-spot#28]
Steps to reproduce
- git clone https://github.com/mono/f-spot.git (used repository tree as of [May 4th](https://github.com/mono/f-spot/tree/2e3ed9b129c9cfed7cf9e53540156a1a4f2a231a) when writing this issue)
- run `autogen.sh` and fail to find all requirements
- add [Mono deb repository](http://www.mono-project.com/docs/getting-started/install/linux/#debian-ubuntu-and-derivatives) to Ubuntu
- frantically keep installing packages until `autogen.sh` doesn't complain
- finally, end up with a successful run of `autogen.sh` and you get `Run 'make' to build F-Spot.` - yay!
- `make`

```
make
Building ./F-Spot.sln
unique/generated/App.custom(17,9): warning CS0618: `GLib.CDeclCallbackAttribute' is obsolete: `You must use the UnmanagedFunctionPointer attribute with value 'CallingConvention.Cdecl'. This attribute does not set the delegate to 'cdecl' correctly'
CSC:  warning CS1616: Option `keyfile' overrides attribute `System.Reflection.AssemblyKeyFileAttribute' given in a source file or added module
TagLib/Audible/Tag.cs(153,21): warning CS0168: The variable `e' is declared but never used
Hyena.Collections/IntervalHeap.cs(282,37): warning CS0108: `Hyena.Collections.IntervalHeap<T>.SyncIntervalHeap.heap' hides inherited member `Hyena.Collections.IntervalHeap<T>.heap'. Use the new keyword if hiding was intended
Banshee.Kernel/IntervalHeap.cs(316,37): warning CS0108: `Banshee.Kernel.IntervalHeap<T>.SyncIntervalHeap.heap' hides inherited member `Banshee.Kernel.IntervalHeap<T>.heap'. Use the new keyword if hiding was intended
Mono.Addins.Setup/RepositoryReaderWriter.cs(539,34): warning CS0612: `Mono.Addins.Description.NativeDependency' is obsolete
Mono.Addins.Setup/RepositoryReaderWriter.cs(946,61): warning CS0612: `Mono.Addins.Description.NativeDependency' is obsolete
Mono.Addins.Setup/AddinInfo.cs(152,45): warning CS0612: `Mono.Addins.Description.NativeDependency' is obsolete
Mono.Addins.Setup/AddinInfo.cs(159,45): warning CS0612: `Mono.Addins.Description.NativeDependency' is obsolete
Mono.Addins.Setup/RepositoryReaderWriter.cs(541,28): warning CS0612: `Mono.Addins.Description.NativeDependency' is obsolete
Mono.Addins.Setup/RepositoryReaderWriter.cs(553,108): warning CS0612: `Mono.Addins.Description.NativeDependency' is obsolete
Mono.Addins.Setup/RepositoryReaderWriter.cs(553,34): warning CS0612: `Mono.Addins.Description.NativeDependency' is obsolete
Mono.Addins.Setup/RepositoryReaderWriter.cs(882,81): warning CS0612: `Mono.Addins.Description.NativeDependency' is obsolete
Mono.Addins.Setup/RepositoryReaderWriter.cs(883,62): warning CS0612: `Mono.Addins.Description.NativeDependency' is obsolete
Mono.Addins.Setup/RepositoryReaderWriter.cs(899,89): warning CS0612: `Mono.Addins.Description.NativeDependency' is obsolete
Mono.Addins.Setup/RepositoryReaderWriter.cs(900,62): warning CS0612: `Mono.Addins.Description.NativeDependency' is obsolete
Mono.Addins.Setup/RepositoryReaderWriter.cs(956,47): warning CS0612: `Mono.Addins.Description.NativeDependency' is obsolete
CSC: error CS1705: Assembly `gdk-sharp, Version=3.0.0.0, Culture=neutral, PublicKeyToken=35e10195dab3c99f' references `glib-sharp, Version=3.0.0.0, Culture=neutral, PublicKeyToken=35e10195dab3c99f' which has a higher version number than imported assembly `glib-sharp, Version=2.12.0.0, Culture=neutral, PublicKeyToken=35e10195dab3c99f'
Makefile:1081: recipe for target 'sln_build' failed
make: *** [sln_build] Error 1
```

**Comment by hzulla** [comment]
Then again, the README.md says `cd build; make`, then `cd lib/libfspot; make`, then `sudo make install`. I've done these steps, too, there was no error. But there was no resulting f-spot.exe.

**Comment by hzulla** [comment]
Bump.

**Comment by decriptor** [comment]
Without installing the latest mono from the mono deb repository I'm now hitting a cairo error. I'll have to look at it some more tomorrow, but this is what I have so far:

sudo apt-get install git
git clone mono/f-spot
sudo apt-get install automake
sudo apt-get install libtool
sudo apt-get install intltool
sudo apt-get install libglib2.0-cil-dev
sudo apt-get install libglib2.0-dev
sudo apt-get install libgconf2-dev libgconf2.0-cil-dev
sudo apt-get install mono-devel
sudo apt-get install libgtk2.0-cil-dev
sudo apt-get install libgnome-keyring1.0-cil-dev
sudo apt-get install libflickrnet-cil-dev
sudo apt-get install libdbus-glib1.0-cil-dev
sudo apt-get install gtk-sharp2-gapi
sudo apt-get install libgnomedesktop2.0-cil-dev
sudo apt-get install libgnome-desktop-dev
sudo apt-get install libjpeg-dev
sudo apt-get install liblcms2-dev
sudo apt-get install libunique-dev
sudo apt-get install libgio2.0-cil-dev
sudo apt-get install libgtk-sharp-beans2.0-cil-dev
sudo apt-get install gnome-icon-theme
sudo apt-get install gnome-doc-utils
sudo apt-get install libcairo1.10-cil
sudo apt-get install monodevelop

bash autogen.sh
make

**Comment by decriptor** [comment]
With the above list I and the Mono deb repository I was able to get it building. I merged a PR which changed one of the requirements from libdbus-glib1.0-cil-dev to libdbus-glib2.0-cil-dev

**Comment by hzulla** [comment]
Thanks.

Sadly, build still fails. Error message is:

    Building ./F-Spot.sln
    CSC: error CS1705: Assembly `gdk-sharp, Version=3.0.0.0, Culture=neutral, PublicKeyToken=35e10195dab3c99f' references `glib-sharp, Version=3.0.0.0, Culture=neutral, PublicKeyToken=35e10195dab3c99f' which has a higher version number than imported assembly `glib-sharp, Version=2.12.0.0, Culture=neutral, PublicKeyToken=35e10195dab3c99f'
    Makefile:1082: recipe for target 'sln_build' failed

**Comment by decriptor** [comment]
I wonder if the problem that you are missing some gtk-sharp 2 related package.

**Comment by codingdave** [comment]
I was able to build f-spot on Ubuntu 15.10 without too much effort. The only mistakes I did were adding version 3 packages when version 2 was required. I also had problems importing some files using the provided taglib-sharp. So I compiled the latest taglib-sharp from the sources.

Dear f-spot team. I am so happy that you maintain that project an I hope I will be able to contribute a bit.

**Comment by decriptor** [comment]
@codingdave thanks, there have been some great contributors from the community lately. My time has been very limited, but I'm hoping to find some more time soon.

Please feel free to test the latest git version and file any bugs that you come across under issues :)

**Comment by mans0954** [comment]
If it's any help, I've built an experimental Debian package for f-spot. There's a binary version for Ubuntu Xenial here:

https://launchpad.net/~christopher-hoskin/+archive/ubuntu/f-spot

Source code here:

https://github.com/mans0954/f-spot/tree/debian/sid

**Comment by codingdave** [comment]
I've tested that package on Ubuntu 16.04. it runs smoothly. Thank you for
providing it. I guess this is of much help because I came to building the
git version only because I couldn't find a ppa with a running version.
Thank you!
Am 22.06.2016 12:56 schrieb "Christopher Hoskin" <notifications@github.com>:

**Comment by dkoeb** [comment]
Closing as Ubuntu 15.04 is quite outdated and builds on newer versions reportedly work.
