### ISSUE TITLE
repeated error message "Source ID not found when attempting to remove it"

### ISSUE THREAD

**Issue by ostroffjh** [mono/f-spot#53]
Running f-spot (compiled from git head) produces many errors like:
Domain: 'GLib' Level: Critical
Message: Source ID 3086 was not found when attempting to remove it
Trace follows:
  at GLib.Log.PrintTraceLogFunction (System.String domain, LogLevelFlags level, System.String message) [0x0000e] in <filename unknown>:0 
  at GLib.Log.<LogFuncTrampoline>m__0 (System.String domain, LogLevelFlags level, System.String message, GLib.LogFunc user_data) [0x00005] in <filename unknown>:0 
  at GLib.Source.g_source_remove (UInt32 ) [0x00000] in <filename unknown>:0 
  at GLib.Source.Remove (UInt32 tag) [0x00031] in <filename unknown>:0 
  at GLib.Idle+IdleProxy.Dispose (Boolean disposing) [0x00018] in <filename unknown>:0 
  at GLib.Idle+IdleProxy.Finalize () [0x00003] in <filename unknown>:0 

although the trace differs widely.  Based on googling, I'm not sure if this is a bug in f-spot (attempt to double free?) or a problem in an underlying library.  Right now, I can only find one report: https://bugs.launchpad.net/ubuntu/+source/gnome-control-center/+bug/1264368

There is an upstream but: https://bugzilla.gnome.org/show_bug.cgi?id=721369  but I can't quite follow all the finger pointing.

This one is not related to f-spot, but does have some interesting (relevant?) comments: http://stackoverflow.com/questions/23199699/glib-critical-source-id-xxx-was-not-found-when-attempting-to-remove-it

It is obviously not critical, but would be nice to solve, as it clutters up debugging output for other problems.

**Comment by dkoeb** [comment]
There were quite some changes since you posted this issue. Do you still experience these errors with the latest source? I can't reproduce them here.

**Comment by genterminl** [comment]
Unfortunately, those errors are still present.  This is with the current git head.  I don't have a lot of time currently, but I'm certainly willing to try some further debugging.

**Comment by genterminl** [comment]
Just compiled again from git head, and these are still present.

**Comment by dkoeb** [comment]
What distro and versions of gtk, glib etc. are you using? The comments on various bug trackers that can be found suggest that this is a problem somewhere in gtk or glib. As I can't see it here (on Arch) I assume that the issue was fixed in newer versions. Based on this I also assume that there is nothing we can do in f-spot to fix it.

**Comment by genterminl** [comment]
Unfortunately, that does make sense.  I'm on Gentoo.  kernel 4.9.6,  glib 2.48.2,  gtk+ 2.24.31 and 3.20.9 (sorry, not sure which is used by f-spot.)   I can upgrade glib to 2.50.3 and gtk to 3.22.5 or 3.22.9 (nothing higher now for 2.x) if you think it might help.

**Comment by genterminl** [comment]
With glib 2.50.3 and gtk+ 2.24.31 and 3.22.9 I still get these errors.  Are there newer versions?  The system I had Arch on had died, and wasn't a good test case since it had an old CPU with a particular set of cup flags no longer supported by Arch.  I suppose I could see about putting Arch in a VBox.

**Comment by genterminl** [comment]
My arch box is dead and gone.  My gentoo box is now at kernel 4.9.30, glib 2.50.3, gtk+ 2.24.31 and 3.22.15.  I still get these errors.  It might also be my imagination, but there do seem to be fewer of them than there used to, although I've never determined exactly which actions generate them.  I just set up a new Manjaro box, so I'll have to see if I can get f-spot installed there to test.

**Comment by genterminl** [comment]
kernel 4.12.5, glib 2.50.3, gtk+ 2.24.31 and 3.22.16, still getting same errors.  Also see the occasional:
  Cairo.Surface is leaking, programmer is missing a call to Dispose
  Set MONO_CAIRO_DEBUG_DISPOSE to track allocation traces
This is with freshly compiled version from git head.

**Comment by decriptor** [comment]
What version of gtk-sharp do you have? it should be something like `2.12.x`.

**Comment by genterminl** [comment]
2.12.21   I might be able to go to 2.12.45 or maybe even a 3.x candidate, but I have no idea if those will actually install correctly for me on Gentoo.  I'm willing to try, if you think it might help.

**Comment by decriptor** [comment]
I'd highly recommend moving to the latest 2.12.x. It doesn't matter what version of 3.x you are running because we are stuck on the 2.12.x branch for now. We'd have to port the whole app to gtk+ 3

**Comment by genterminl** [comment]
Bingo!  2.12.45, and I see no more Source ID errors.  I do still get (a small number of)
  Cairo.Surface is leaking, programmer is missing a call to Dispose
  Set MONO_CAIRO_DEBUG_DISPOSE to track allocation traces
and one
  GdkPixbuf-WARNING **: GdkPixbufLoader finalized without calling gdk_pixbuf_loader_close() - this is not allowed. You must explicitly end the data stream to the loader before dropping the last reference.
and two
  Gtk-CRITICAL **: IA__gtk_style_detach: assertion 'style->attach_count > 0' failed
(this is just launching f-spot and scrolling along my timeline.)

As those are not related to the original error of this Issue, I'll go ahead and close this one as fixed by the gtk-sharp upgrade.

**Comment by decriptor** [comment]
Those are unrelated. I've enabled stuff locally to try and track those down and fix them.
